name: Deploy Go Web App to EC2

on:
  push:
    branches:
      - main  # or the branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: ${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull sudhinsuresh9526/go-web-app:v1
          docker stop $(docker ps -q --filter ancestor=sudhinsuresh9526/go-web-app:v1) || true
          docker rm $(docker ps -a -q --filter ancestor=sudhinsuresh9526/go-web-app:v1) || true
          docker run -d -p 9001:8080 sudhinsuresh9526/go-web-app:v1
        EOF
